### ISSUE TITLE
Create a tag/release?

### ISSUE THREAD

**Issue by jaredramirez** [DeterminateSystems/nix-installer-action#15]
Hey there!

This action (and project to make Nix easier to use/learn in general) is awesome!

How stable is this action at the moment? If it's pretty stable, it would be great to cut a release. I want to start using this on some work repository actions, but for stability it would be great to tie the action to a tag rather than `main`.

Is there any plan for this in the near future?

**Comment by InternetUnexplorer** [comment]
I haven't tried it myself, but it [seems like there's already a tag](https://github.com/DeterminateSystems/nix-installer-action/tree/v1), unless I'm missing something I think that should work?

**Comment by cole-h** [comment]
We just forgot to update the README to call out the tagged `v1` :sweat_smile: 

I've opened https://github.com/DeterminateSystems/nix-installer-action/pull/17 to fix that.
