### ISSUE TITLE
Compare to other install actions

### ISSUE THREAD

**Issue by NobbZ** [DeterminateSystems/nix-installer-action#20]
Is there a comparison between the different installer actions?

I'd like to know what I gain or loose by using this action over eg. [the one by cachix](https://github.com/cachix/install-nix-action).

**Comment by Hoverbear** [comment]
There is not.

We list all installation differences to the official Nix install scripts here: https://github.com/DeterminateSystems/nix-installer#installation-differences -- Spoiler: There aren't many!

The biggest difference is mostly that this project tries to use Rust over bash where possible.

Ultimately both actions do their job and install Nix an equally capable Nix in the same way. Choose either. :)
