### ISSUE TITLE
`$HOME/.nix-profile/bin` not in PATH

### ISSUE THREAD

**Issue by lovesegfault** [DeterminateSystems/nix-installer-action#21]
This causes cachix-action to fail when using Nix 2.15: https://github.com/cachix/cachix-action/issues/146

I think `echo "$HOME/.nix-profile/bin" >> "$GITHUB_PATH"` is warranted somewhere, though I am uncertain whether that should happen here or in the installer.

**Comment by lovesegfault** [comment]
Ah, it's this issue: https://github.com/DeterminateSystems/nix-installer/issues/475

Note, however, that this line here would also need updating: https://github.com/DeterminateSystems/nix-installer-action/blob/9b252454a8d70586c4ee7f163bf4bb1e9de3d763/action.yml#LL121C5-L121C5

**Comment by lovesegfault** [comment]
This issue isn't resolved yet, I tried bumping to `v3` and removing my workaround in this commit: https://github.com/lovesegfault/nix-config/commit/68886670c7cb253b07d4f967df871251cca57d2b

But the issue persisted, and the build failed: https://github.com/lovesegfault/nix-config/actions/runs/5101945610/jobs/9171171410

**Comment by Hoverbear** [comment]
We determined https://github.com/DeterminateSystems/nix-installer/pull/482 was required as well, I'll be releasing it Tuesday (https://github.com/DeterminateSystems/nix-installer/pull/484) since most folks are out today on various holidays.

**Comment by lovesegfault** [comment]
Removed my workaround and the build still works!

I did need to explicitly use `nix-installer-tag: "v0.9.1"`; otherwise it picked up the 0.8 release.

Thanks!
