### ISSUE TITLE
Consider using tool-cache

### ISSUE THREAD

**Issue by Hoverbear** [DeterminateSystems/nix-installer-action#36]
We may be able to use https://github.com/actions/toolkit/tree/main/packages/tool-cache to use some github smart caching and simplify some code.

Currently the issue is that we can't easily know when to cachebust, since the action typically gets the latest installer. Unfortunately the tool cache doesn't seem to have expiry settings, so it's hard to properly judge when the user should get a new nix-installer binary.

**Comment by grahamc** [comment]
We do this now :). But not with tool-cache ... that does something different, confusingly.
