### ISSUE TITLE
`max-jobs` is 1

### ISSUE THREAD

**Issue by srid** [DeterminateSystems/nix-installer-action#37]
`nix show-config | grep max-jobs` is set to 1 on github actions. Isn't this a cause for concern? Because that would limit the number of concurrent downloads to being 1, slowing down the CI job as a consequence.

<img width="185" alt="image" src="https://github.com/DeterminateSystems/nix-installer-action/assets/3998/f47fe162-12e6-46c1-acb0-b592abb23217">

https://github.com/srid/nix-health/actions/runs/5743692748/job/15568517152#step:4:79

**Comment by srid** [comment]
The ubuntu VM has 2-cores,
https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources

So at minimum it seems this installer is not setting `max-jobs` to "auto".

**Comment by Hoverbear** [comment]
We're not setting this value at all! `1` is the default: https://nixos.org/manual/nix/stable/command-ref/conf-file.html#conf-max-jobs

**Comment by srid** [comment]
Ah, interesting. So the default is `"auto"` [_only_ in NixOS](https://search.nixos.org/options?channel=23.05&show=nix.settings.max-jobs&from=0&size=50&sort=relevance&type=packages&query=max-jobs).

Would it be a good feature addition to have nix-installer set it to `"auto"` during install? Or if explicitly asked for by the user. We were wondering why, on our Macs (but not on NixOS machines), we have to explicitly use `-j auto` everytime to speed up the Nix builds.

**Comment by Hoverbear** [comment]
I think it might be!

**Comment by grahamc** [comment]
Nix is now using "auto" by default, so this should be all set. Thanks!
