### ISSUE TITLE
Update to `node20`

### ISSUE THREAD

**Issue by lovesegfault** [DeterminateSystems/nix-installer-action#40]
The action is still on `node16`, but by default configured runners on NixOS only come with `node20`, causing the action to fail.

It should probably be moved to `node20`, if there are no drawbacks?

https://github.com/DeterminateSystems/nix-installer-action/blob/07ebb8d2749aa2fac2baae7d1cfa011e4acfd8d1/action.yml#L108-L111

**Comment by grahamc** [comment]
Released in v6 :).
